language: elixir
matrix:
  include:
    - otp_release: 19.0
      elixir: 1.3.2
sudo: false
before_install:
  cd vivaldi
before_script:
  epmd -daemon
script:
  MIX_ENV=test mix do deps.get, compile, coveralls.travis --exclude multi_node
